### ISSUE TITLE
Stuck at building node-lemmer

### ISSUE THREAD

**Issue by pranita-s** [noduslabs/infranodus#181]
Hi, I am unable to resolve the issue of unsuccessful node-lemmer build.
Following is the error-

user@ubuntuvm:~/infranodus/node_modules$ sudo npm build node-lemmer
[sudo] password for user: 

> node-lemmer@0.1.0 install /home/user/infranodus/node_modules/node-lemmer
> node-gyp rebuild

make: Entering directory `/home/user/infranodus/node_modules/node-lemmer/build'
  CC(target) Release/obj.target/node_lemmer/src/automaton_basic.o
../src/automaton_basic.c: In function ‘stack_push’:
../src/automaton_basic.c:250:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (st->current + 1 < st->reserved)
                      ^
../src/automaton_basic.c: In function ‘MAFSA_str_to_int’:
../src/automaton_basic.c:332:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(data->processed < data->data_sz)
                     ^
../src/automaton_basic.c: In function ‘MAFSA_str_to_int_pair’:
../src/automaton_basic.c:374:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(valid && (data->processed < data->data_sz/2))
                               ^
  CC(target) Release/obj.target/node_lemmer/src/lemmatizer.o
../src/lemmatizer.c: In function ‘turglem_build_form’:
../src/lemmatizer.c:196:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if(new_s_sz > sz_s_out)
              ^
  CC(target) Release/obj.target/node_lemmer/src/paradigms.o
  CC(target) Release/obj.target/node_lemmer/src/prediction.o
  CC(target) Release/obj.target/node_lemmer/src/russian/charset_adapters.o
../src/russian/charset_adapters.c: In function ‘LEM_RUSSIAN_conv_string_to_letters_cp1251’:
../src/russian/charset_adapters.c:14:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while (*i && (pos < sz))
                    ^
../src/russian/charset_adapters.c: In function ‘LEM_RUSSIAN_conv_letters_to_string_cp1251’:
../src/russian/charset_adapters.c:45:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while ((pos < sz_l) && (pos < sz_s - 1))
              ^
../src/russian/charset_adapters.c:45:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while ((pos < sz_l) && (pos < sz_s - 1))
                              ^
../src/russian/charset_adapters.c: In function ‘LEM_RUSSIAN_conv_string_to_letters_utf8’:
../src/russian/charset_adapters.c:70:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while (*i && (pos < sz))
                    ^
../src/russian/charset_adapters.c: In function ‘LEM_RUSSIAN_conv_string_to_letters_koi8r’:
../src/russian/charset_adapters.c:160:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while (*i && (pos < sz))
                    ^
../src/russian/charset_adapters.c: In function ‘LEM_RUSSIAN_conv_letters_to_string_koi8r’:
../src/russian/charset_adapters.c:191:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while ((pos < sz_l) && (pos < sz_s - 1))
              ^
../src/russian/charset_adapters.c:191:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while ((pos < sz_l) && (pos < sz_s - 1))
                              ^
  CC(target) Release/obj.target/node_lemmer/src/english/charset_adapters.o
../src/english/charset_adapters.c: In function ‘LEM_ENGLISH_conv_string_to_letters_utf8’:
../src/english/charset_adapters.c:14:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while (*i && (pos < sz))
                    ^
../src/english/charset_adapters.c: In function ‘LEM_ENGLISH_conv_letters_to_string_utf8’:
../src/english/charset_adapters.c:47:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while ((pos < sz_l) && (pos < sz_s - 1))
              ^
../src/english/charset_adapters.c:47:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  while ((pos < sz_l) && (pos < sz_s - 1))
                              ^
  CXX(target) Release/obj.target/node_lemmer/src/node-lemmer.o
../src/node-lemmer.cc:14:33: error: expected class-name before ‘,’ token
 class Lemmer : public ObjectWrap, public tl::lemmatizer {
                                 ^
../src/node-lemmer.cc:42:36: error: ‘Arguments’ does not name a type
     static Handle<Value> New(const Arguments& args) {
                                    ^
../src/node-lemmer.cc:42:47: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
     static Handle<Value> New(const Arguments& args) {
                                               ^
../src/node-lemmer.cc:68:42: error: ‘Arguments’ does not name a type
     static Handle<Value> Lemmatize(const Arguments& args) {
                                          ^
../src/node-lemmer.cc:68:53: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
     static Handle<Value> Lemmatize(const Arguments& args) {
                                                     ^
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h: In static member function ‘static void Lemmer::Initialize(v8::Handle<v8::Object>)’:
/home/user/.node-gyp/5.11.1/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/node-lemmer.cc:17:21: error: within this context
         HandleScope scope;
                     ^
../src/node-lemmer.cc:18:62: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handle<v8::Value> (&)(const int&))’
         Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                              ^
../src/node-lemmer.cc:18:62: note: candidate is:
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h:4348:34: note: static v8::Local<v8::FunctionTemplate> v8::FunctionTemplate::New(v8::Isolate*, v8::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>, int)
   static Local<FunctionTemplate> New(
                                  ^
/home/user/.node-gyp/5.11.1/include/node/v8.h:4348:34: note:   no known conversion for argument 1 from ‘v8::Handle<v8::Value>(const int&) {aka v8::Local<v8::Value>(const int&)}’ to ‘v8::Isolate*’
../src/node-lemmer.cc:21:85: error: no matches converting function ‘Lemmatize’ to type ‘v8::FunctionCallback {aka void (*)(const class v8::FunctionCallbackInfo<v8::Value>&)}’
         NODE_SET_PROTOTYPE_METHOD(t, "lemmatizeEng", Lemmatize<english_utf8_adapter>);
                                                                                     ^
../src/node-lemmer.cc:94:18: note: candidates are: template<class adapter> std::vector<Lemmer::Form> Lemmer::Lemmatize(const string&)
     vector<Form> Lemmatize(const string& word) {
                  ^
../src/node-lemmer.cc:68:26: note:                 template<class adapter> static v8::Handle<v8::Value> Lemmer::Lemmatize(const int&)
     static Handle<Value> Lemmatize(const Arguments& args) {
                          ^
../src/node-lemmer.cc:22:85: error: no matches converting function ‘Lemmatize’ to type ‘v8::FunctionCallback {aka void (*)(const class v8::FunctionCallbackInfo<v8::Value>&)}’
         NODE_SET_PROTOTYPE_METHOD(t, "lemmatizeRus", Lemmatize<russian_utf8_adapter>);
                                                                                     ^
../src/node-lemmer.cc:94:18: note: candidates are: template<class adapter> std::vector<Lemmer::Form> Lemmer::Lemmatize(const string&)
     vector<Form> Lemmatize(const string& word) {
                  ^
../src/node-lemmer.cc:68:26: note:                 template<class adapter> static v8::Handle<v8::Value> Lemmer::Lemmatize(const int&)
     static Handle<Value> Lemmatize(const Arguments& args) {
                          ^
../src/node-lemmer.cc:24:21: error: ‘NewSymbol’ is not a member of ‘v8::String’
         target->Set(String::NewSymbol("Lemmer"), t->GetFunction());
                     ^
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h: In static member function ‘static v8::Handle<v8::Value> Lemmer::New(const int&)’:
/home/user/.node-gyp/5.11.1/include/node/v8.h:889:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/node-lemmer.cc:43:21: error: within this context
         HandleScope scope;
                     ^
../src/node-lemmer.cc:45:19: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
          if (args.Length() < 2 || !args[0]->IsString() || !args[1]->IsString())
                   ^
../src/node-lemmer.cc:45:42: error: invalid types ‘const int[int]’ for array subscript
          if (args.Length() < 2 || !args[0]->IsString() || !args[1]->IsString())
                                          ^
../src/node-lemmer.cc:45:66: error: invalid types ‘const int[int]’ for array subscript
          if (args.Length() < 2 || !args[0]->IsString() || !args[1]->IsString())
                                                                  ^
../src/node-lemmer.cc:46:56: error: ‘New’ is not a member of ‘v8::String’
             return ThrowException(Exception::TypeError(String::New("Wrong args")));
                                                        ^
../src/node-lemmer.cc:46:82: error: ‘ThrowException’ was not declared in this scope
             return ThrowException(Exception::TypeError(String::New("Wrong args")));
                                                                                  ^
../src/node-lemmer.cc:48:41: error: invalid types ‘const int[int]’ for array subscript
         string dict = ToStdString(args[0]);
                                         ^
../src/node-lemmer.cc:49:46: error: invalid types ‘const int[int]’ for array subscript
         string paradigms = ToStdString(args[1]);
                                              ^
../src/node-lemmer.cc:51:18: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
         if (args.Length() == 3 && args[2]->IsString())
                  ^
../src/node-lemmer.cc:51:41: error: invalid types ‘const int[int]’ for array subscript
         if (args.Length() == 3 && args[2]->IsString())
                                         ^
../src/node-lemmer.cc:52:41: error: invalid types ‘const int[int]’ for array subscript
             predict = ToStdString(args[2]);
                                         ^
../src/node-lemmer.cc:55:17: error: ‘class Lemmer’ has no member named ‘Wrap’
         lemmer->Wrap(args.This());
                 ^
../src/node-lemmer.cc:55:27: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
         lemmer->Wrap(args.This());
                           ^
../src/node-lemmer.cc:56:21: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
         return args.This();
                     ^
../src/node-lemmer.cc: In constructor ‘Lemmer::Lemmer(const string&, const string&, const string&)’:
../src/node-lemmer.cc:60:11: error: class ‘Lemmer’ does not have any field named ‘ObjectWrap’
         : ObjectWrap()
           ^
../src/node-lemmer.cc: In static member function ‘static v8::Handle<v8::Value> Lemmer::Lemmatize(const int&)’:
../src/node-lemmer.cc:69:26: error: ‘ObjectWrap’ has not been declared
         Lemmer* lemmer = ObjectWrap::Unwrap<Lemmer>(args.This());
                          ^
../src/node-lemmer.cc:69:51: error: expected primary-expression before ‘>’ token
         Lemmer* lemmer = ObjectWrap::Unwrap<Lemmer>(args.This());
                                                   ^
../src/node-lemmer.cc:69:58: error: request for member ‘This’ in ‘args’, which is of non-class type ‘const int’
         Lemmer* lemmer = ObjectWrap::Unwrap<Lemmer>(args.This());
                                                          ^
../src/node-lemmer.cc:72:18: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
         if (args.Length() != 1 || !args[0]->IsString())
                  ^
../src/node-lemmer.cc:72:42: error: invalid types ‘const int[int]’ for array subscript
         if (args.Length() != 1 || !args[0]->IsString())
                                          ^
../src/node-lemmer.cc:73:56: error: ‘New’ is not a member of ‘v8::String’
             return ThrowException(Exception::TypeError(String::New("Wrong args")));
                                                        ^
../src/node-lemmer.cc:73:82: error: there are no arguments to ‘ThrowException’ that depend on a template parameter, so a declaration of ‘ThrowException’ must be available [-fpermissive]
             return ThrowException(Exception::TypeError(String::New("Wrong args")));
                                                                                  ^
../src/node-lemmer.cc:73:82: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../src/node-lemmer.cc:75:41: error: invalid types ‘const int[int]’ for array subscript
         string word = ToStdString(args[0]);
                                         ^
../src/node-lemmer.cc:77:56: error: ‘New’ is not a member of ‘v8::String’
             return ThrowException(Exception::TypeError(String::New("Passed word is empty")));
                                                        ^
../src/node-lemmer.cc:77:92: error: there are no arguments to ‘ThrowException’ that depend on a template parameter, so a declaration of ‘ThrowException’ must be available [-fpermissive]
             return ThrowException(Exception::TypeError(String::New("Passed word is empty")));
                                                                                            ^
../src/node-lemmer.cc:82:55: error: no matching function for call to ‘v8::Array::New(std::vector<Lemmer::Form>::size_type)’
         Local<Array> res = Array::New(mainforms.size());
                                                       ^
../src/node-lemmer.cc:82:55: note: candidate is:
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h:2962:23: note: static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int) <near match>
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
/home/user/.node-gyp/5.11.1/include/node/v8.h:2962:23: note:   no known conversion for argument 1 from ‘std::vector<Lemmer::Form>::size_type {aka unsigned int}’ to ‘v8::Isolate*’
../src/node-lemmer.cc:84:46: error: no matching function for call to ‘v8::Object::New()’
             Local<Object> form = Object::New();
                                              ^
../src/node-lemmer.cc:84:46: note: candidate is:
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h:2930:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/user/.node-gyp/5.11.1/include/node/v8.h:2930:24: note:   candidate expects 1 argument, 0 provided
../src/node-lemmer.cc:85:42: error: there are no arguments to ‘NODE_PSYMBOL’ that depend on a template parameter, so a declaration of ‘NODE_PSYMBOL’ must be available [-fpermissive]
             form->Set(NODE_PSYMBOL("text"), String::New(mainforms[i].text.c_str()));
                                          ^
../src/node-lemmer.cc:85:45: error: ‘New’ is not a member of ‘v8::String’
             form->Set(NODE_PSYMBOL("text"), String::New(mainforms[i].text.c_str()));
                                             ^
../src/node-lemmer.cc:86:50: error: there are no arguments to ‘NODE_PSYMBOL’ that depend on a template parameter, so a declaration of ‘NODE_PSYMBOL’ must be available [-fpermissive]
             form->Set(NODE_PSYMBOL("partOfSpeech"), Integer::New(mainforms[i].partOfSpeech));
                                                  ^
../src/node-lemmer.cc:86:91: error: no matching function for call to ‘v8::Integer::New(u_int8_t&)’
             form->Set(NODE_PSYMBOL("partOfSpeech"), Integer::New(mainforms[i].partOfSpeech));
                                                                                           ^
../src/node-lemmer.cc:86:91: note: candidate is:
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h:2496:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/user/.node-gyp/5.11.1/include/node/v8.h:2496:25: note:   candidate expects 2 arguments, 1 provided
../src/node-lemmer.cc:87:36: error: no matching function for call to ‘v8::Integer::New(size_t&)’
             res->Set(Integer::New(i), form);
                                    ^
../src/node-lemmer.cc:87:36: note: candidate is:
In file included from ../src/node-lemmer.cc:1:0:
/home/user/.node-gyp/5.11.1/include/node/v8.h:2496:25: note: static v8::Local<v8::Integer> v8::Integer::New(v8::Isolate*, int32_t)
   static Local<Integer> New(Isolate* isolate, int32_t value);
                         ^
/home/user/.node-gyp/5.11.1/include/node/v8.h:2496:25: note:   candidate expects 2 arguments, 1 provided
../src/node-lemmer.cc:90:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(res);
                      ^
make: *** [Release/obj.target/node_lemmer/src/node-lemmer.o] Error 1
make: Leaving directory`/home/user/infranodus/node_modules/node-lemmer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/infranodus/node_modules/node-lemmer
gyp ERR! node -v v5.11.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "build" "node-lemmer"
npm ERR! node v5.11.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! node-lemmer@0.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-lemmer@0.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-lemmer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-lemmer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-lemmer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/infranodus/node_modules/npm-debug.log

I tried installing different versions of NodeJS but the error persists.
How can this be resolved ??
Thanks in advance !

**Comment by deemeetree** [comment]
Hello, somehow missed this one. Could you please tell me if the issue was resolved?

**Comment by deemeetree** [comment]
Hello @pranita-s – I just updated InfraNodus and connected it to a new lemmer which doesn't need to be built again. You can find the current version on `newlemmer` branch but I will soon merge it to master. Just letting you know

**Comment by pranita-s** [comment]
@deemeetree Thanks !
