### ISSUE TITLE
Booted and can't log in (400 & 500 error)

### ISSUE THREAD

**Issue by mateicanavra** [noduslabs/infranodus#225]
Hi there!

I got booted from the site with a 500 Bad Gateway error about an hour ago. After trying to refresh multiple times, no luck, so I cleared the cache & cookies. That brought me back to the login page, which I can now access, but I still can't log in.

Checked this on a friend's computer (never accessed infranodus before) and the same issue persists.

Does the site happen to be down?

**Comment by deemeetree** [comment]
@mateicanavra 

yes, there's been some technical problems yesterday, which have been fixed now. so all is good.

thank you for letting me know!

**Comment by mateicanavra** [comment]
Thanks for the quick update! Much appreciated
