### ISSUE TITLE
Add Google Scholar analysis

### ISSUE THREAD

**Issue by deemeetree** [noduslabs/infranodus#235]
Using https://github.com/VT-CHCI/google-scholar

Plus graphmark

**Comment by deemeetree** [comment]
If the text has to breaks every snippet has to have a reference link separately

**Comment by deemeetree** [comment]
Or maybe extract the link (or a reference) and put it into the statement's origin field.

**Comment by deemeetree** [comment]
If the text is not too long, can be also one statement

**Comment by mateusrangel** [comment]
Hey @deemeetree , i am interested in using infranodus with patent/papers data. In my company we are pondering the use of infranodus in our existing business intelligence system based on patents/paper as a graph visualization. 

We liked your TNA algorithm to generate graphs from text as opose from the boring cloud of words. There is a easy way to embedd infranodus in our system? 

And for the google scholar support, this could be my first open source contribution!

**Comment by deemeetree** [comment]
@mateusrangel — could you please show me your system or give access to it and also give me the tech specs? we could then see what would be the easiest and the best way to implement infranodus inside. 

you can send me all the info over the email: info@noduslabs.com 

thanks!

**Comment by mateusrangel** [comment]
> Using https://github.com/VT-CHCI/google-scholar
> 
> Plus graphmark

Nice scholar web-scrapper, this is what we do when the data-source don't provide a API. What is graphmark?
