### ISSUE TITLE
I can't log in to local

### ISSUE THREAD

**Issue by wmqsoft** [noduslabs/infranodus#274]
I created a new account in infranodus site.

And installed infranodus on my local machine, installed environment and tried to login with the account.

However it says "Wrong username / password pair. Please, try again."

And also I couldn't create a new account on my local.

Any ideas?

**Comment by deemeetree** [comment]
Hi @wmqsoft — could you please tell me what your account name is? We will sort it out.

**Comment by shaobsh** [comment]
@deemeetree I also need access, my username is shaobsh
thank you!
