### ISSUE TITLE
Is it possible to ask that the "express" package get updated in Infranodus?

### ISSUE THREAD

**Issue by StoltHD** [noduslabs/infranodus#300]
I get a few "High" security warnings  and one "Critical", but if I try to update this, Infranodus do not work anymore...

This is on a windows 10 Computer, 64-bit, build 19008 and Node.js ver. v12.12.0

If there anyone knows about a easy fix for a none developer, please tell... thanks
.................................................................................................

There are also some depricated modules used...
..........................................
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules\connect\lib\middleware\bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules\connect\lib\middleware\multipart.js:86:15
connect deprecated methodOverride: use method-override npm module instead app.js:64:17
express-session deprecated req.secret; provide secret option node_modules\connect\lib\middleware\session.js:33:10

..................................................................................................

............................................
# Run  npm install express@4.17.1  to resolve 20 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change

  High            Regular Expression Denial of Service

  Package         negotiator

  Dependency of   express

  Path            express > connect > compression > accepts > negotiator

  More info       https://npmjs.com/advisories/106

  High            Regular Expression Denial of Service

  Package         negotiator

  Dependency of   express

  Path            express > connect > serve-index > accepts > negotiator

  More info       https://npmjs.com/advisories/106

  High            Regular Expression Denial of Service

  Package         fresh

  Dependency of   express

  Path            express > connect > fresh

  More info       https://npmjs.com/advisories/526

  High            Regular Expression Denial of Service

  Package         fresh

  Dependency of   express

  Path            express > connect > serve-favicon > fresh

  More info       https://npmjs.com/advisories/526

  High            Regular Expression Denial of Service

  Package         fresh

  Dependency of   express

  Path            express > connect > serve-static > send > fresh

  More info       https://npmjs.com/advisories/526

  High            Regular Expression Denial of Service

  Package         fresh

  Dependency of   express

  Path            express > fresh

  More info       https://npmjs.com/advisories/526

  High            Regular Expression Denial of Service

  Package         fresh

  Dependency of   express

  Path            express > send > fresh

  More info       https://npmjs.com/advisories/526

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > body-parser > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > compression > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > connect-timeout > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > express-session > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > finalhandler > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > morgan > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > connect > serve-index > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > debug

  More info       https://npmjs.com/advisories/534

  Low             Regular Expression Denial of Service

  Package         debug

  Dependency of   express

  Path            express > send > debug

  More info       https://npmjs.com/advisories/534

  Moderate        Regular Expression Denial of Service

  Package         mime

  Dependency of   express

  Path            express > send > mime

  More info       https://npmjs.com/advisories/535

  High            Out-of-bounds Read

  Package         base64-url

  Dependency of   express

  Path            express > connect > express-session > uid-safe > base64-url

  More info       https://npmjs.com/advisories/660

  Moderate        Code Injection

  Package         morgan

  Dependency of   express

  Path            express > connect > morgan

  More info       https://npmjs.com/advisories/736

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Directory Traversal

  Package         send

  Patched in      >= 0.8.4

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > send

  More info       https://npmjs.com/advisories/32

  Low             Root Path Disclosure

  Package         send

  Patched in      >=0.11.1

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > send

  More info       https://npmjs.com/advisories/56

  High            Regular Expression Denial of Service

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > glob > minimatch

  More info       https://npmjs.com/advisories/118

  High            Regular Expression Denial of Service

  Package         minimatch

  Patched in      >=3.0.2

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > mocha > glob > minimatch

  More info       https://npmjs.com/advisories/118

  Critical        Command Injection

  Package         growl

  Patched in      >=1.10.2

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > mocha > growl

  More info       https://npmjs.com/advisories/146

  Low             Large gzip Denial of Service

  Package         superagent

  Patched in      >=3.7.0

  Dependency of   node-neo4j

  Path            node-neo4j > superagent

  More info       https://npmjs.com/advisories/479

  High            Regular Expression Denial of Service

  Package         fresh

  Patched in      >= 0.5.2

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > send > fresh

  More info       https://npmjs.com/advisories/526

  Moderate        Regular Expression Denial of Service

  Package         mime

  Patched in      >= 1.4.1 < 2.0.0 || >= 2.0.3

  Dependency of   node-neo4j

  Path            node-neo4j > superagent > form-data > mime

  More info       https://npmjs.com/advisories/535

  Moderate        Regular Expression Denial of Service

  Package         mime

  Patched in      >= 1.4.1 < 2.0.0 || >= 2.0.3

  Dependency of   node-neo4j

  Path            node-neo4j > superagent > mime

  More info       https://npmjs.com/advisories/535

  Moderate        Regular Expression Denial of Service

  Package         mime

  Patched in      >= 1.4.1 < 2.0.0 || >= 2.0.3

  Dependency of   phpmorphy

  Path            phpmorphy > phpjs > send > mime

  More info       https://npmjs.com/advisories/535

  High            Regular Expression Denial of Service

  Package         string

  Patched in      No patch available

  Dependency of   string

  Path            string

  More info       https://npmjs.com/advisories/536

  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   google

  Path            google > cheerio > lodash

  More info       https://npmjs.com/advisories/577

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.11

  Dependency of   google

  Path            google > cheerio > lodash

  More info       https://npmjs.com/advisories/782

  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.12

  Dependency of   google

  Path            google > cheerio > lodash

  More info       https://npmjs.com/advisories/1065

  Moderate        Prototype Pollution

  Package         extend

  Patched in      >=2.0.2 <3.0.0 || >=3.0.2

  Dependency of   node-neo4j

  Path            node-neo4j > superagent > extend

  More info       https://npmjs.com/advisories/996

found 35 vulnerabilities (14 low, 6 moderate, 14 high, 1 critical) in 3269 scanned packages
  20 vulnerabilities require semver-major dependency updates.
  15 vulnerabilities require manual review. See the full report for details.

**Comment by deemeetree** [comment]
Hey @StoltHD — I just updated the Express package and other packages that had references to vulnerabilities. The current version is now up-to-date, you can update your local one. 

9aaacdce

**Comment by deemeetree** [comment]
This is the final update with all the fixes: 62a785a

**Comment by StoltHD** [comment]
Thank you, I will keep on testing this ... Great job, I really like the idea behind this project...
